services:
  db:
    build:
      context: ./MYSQL
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: master
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - db_network
    ports:
      - 3306:3306

  flask:
    build: .
    command: python3 -m flask run --host=0.0.0.0 --port=8000 --debug
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - db_network
    depends_on:
      - db

networks:
  db_network:
    driver: bridge